scheme: "Tokyo Night night"
author: "MichaÃ«l Ball"
base00: "#16161e"
base01: "#1a1b26"
base02: "#2f3549"
base03: "#444b6a"
base04: "#787c99"
base05: "#c0caf5"
base06: "#cbccd1"
base07: "#d5d6db"
base08: "#f7768e" # red
base09: "#ff9e64" # orange
base0A: "#e0af68" # yellow
base0B: "#9ece6a" # green
base0C: "#7dcfff" # cyan
base0D: "#7aa2f7" # blue
base0E: "#bb9af7" # purple
base0F: "#73daca" # ?
